// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldForge.Infrastructure.Persistence;

#nullable disable

namespace WorldForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorldForgeDbContext))]
    partial class WorldForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WorldForge.Core.Entities.Contradiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DetectionRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceExcerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suggestion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetExcerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Contradictions");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.EntityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EndOffset")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartOffset")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("EntityLinks");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.EntityRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToEntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EntityRelationships");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.EntityTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("EntityTags");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Embedding")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Notes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Note");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorldForge.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantTemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Creative.Entities.ManuscriptDocument", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ManuscriptDocument");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Creative.Entities.TimelineEvent", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<string>("EraName")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SortKey")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TimelineEvent");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Creative.Entities.WorldCharacter", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alignment")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("WorldCharacter");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Creative.Entities.WorldFaction", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Notes", t =>
                        {
                            t.Property("CustomFieldsJson")
                                .HasColumnName("WorldFaction_CustomFieldsJson");
                        });

                    b.HasDiscriminator().HasValue("WorldFaction");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Creative.Entities.WorldItem", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Notes", t =>
                        {
                            t.Property("CustomFieldsJson")
                                .HasColumnName("WorldItem_CustomFieldsJson");

                            t.Property("Name")
                                .HasColumnName("WorldItem_Name");
                        });

                    b.HasDiscriminator().HasValue("WorldItem");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Creative.Entities.WorldLocation", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<string>("CoordinatesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("TEXT");

                    b.ToTable("Notes", t =>
                        {
                            t.Property("CustomFieldsJson")
                                .HasColumnName("WorldLocation_CustomFieldsJson");

                            t.Property("Name")
                                .HasColumnName("WorldLocation_Name");
                        });

                    b.HasDiscriminator().HasValue("WorldLocation");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Health.Entities.DoctorVisit", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SortKey")
                        .HasColumnType("INTEGER");

                    b.ToTable("Notes", t =>
                        {
                            t.Property("EventDate")
                                .HasColumnName("DoctorVisit_EventDate");

                            t.Property("RelatedEntityIds")
                                .HasColumnName("DoctorVisit_RelatedEntityIds");

                            t.Property("SortKey")
                                .HasColumnName("DoctorVisit_SortKey");
                        });

                    b.HasDiscriminator().HasValue("DoctorVisit");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Health.Entities.HealthNote", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.HasDiscriminator().HasValue("HealthNote");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Health.Entities.SymptomRecord", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SymptomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SymptomRecord");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Legacy.Entities.DigitalAccount", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Notes", t =>
                        {
                            t.Property("CustomFieldsJson")
                                .HasColumnName("DigitalAccount_CustomFieldsJson");
                        });

                    b.HasDiscriminator().HasValue("DigitalAccount");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Legacy.Entities.Letter", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Letter");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Legacy.Entities.LifeEvent", b =>
                {
                    b.HasBaseType("WorldForge.Core.Entities.Note");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SortKey")
                        .HasColumnType("INTEGER");

                    b.ToTable("Notes", t =>
                        {
                            t.Property("EventDate")
                                .HasColumnName("LifeEvent_EventDate");

                            t.Property("RelatedEntityIds")
                                .HasColumnName("LifeEvent_RelatedEntityIds");

                            t.Property("SortKey")
                                .HasColumnName("LifeEvent_SortKey");
                        });

                    b.HasDiscriminator().HasValue("LifeEvent");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.Contradiction", b =>
                {
                    b.HasOne("WorldForge.Core.Entities.Project", "Project")
                        .WithMany("Contradictions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.EntityLink", b =>
                {
                    b.HasOne("WorldForge.Core.Tenants.Creative.Entities.ManuscriptDocument", "SourceDocument")
                        .WithMany("EntityLinks")
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldForge.Core.Entities.Note", "TargetEntity")
                        .WithMany()
                        .HasForeignKey("TargetEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceDocument");

                    b.Navigation("TargetEntity");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.EntityRelationship", b =>
                {
                    b.HasOne("WorldForge.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.EntityTag", b =>
                {
                    b.HasOne("WorldForge.Core.Entities.Note", "Note")
                        .WithMany("Tags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.Note", b =>
                {
                    b.HasOne("WorldForge.Core.Entities.Project", "Project")
                        .WithMany("Notes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.Project", b =>
                {
                    b.OwnsOne("WorldForge.Core.Entities.ProjectSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AutoDetectOnSave")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DefaultEra")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreferredOllamaModel")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("WorldForge.Core.Entities.Note", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("WorldForge.Core.Entities.Project", b =>
                {
                    b.Navigation("Contradictions");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("WorldForge.Core.Tenants.Creative.Entities.ManuscriptDocument", b =>
                {
                    b.Navigation("EntityLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
